//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoWeb2.WSAula {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/TrabalhoWeb2.Models")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Agenda", Namespace="http://schemas.datacontract.org/2004/07/TrabalhoWeb2.Models")]
    [System.SerializableAttribute()]
    public partial class Agenda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgendaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataCompromissoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgendaId {
            get {
                return this.AgendaIdField;
            }
            set {
                if ((this.AgendaIdField.Equals(value) != true)) {
                    this.AgendaIdField = value;
                    this.RaisePropertyChanged("AgendaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataCompromisso {
            get {
                return this.DataCompromissoField;
            }
            set {
                if ((this.DataCompromissoField.Equals(value) != true)) {
                    this.DataCompromissoField = value;
                    this.RaisePropertyChanged("DataCompromisso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Participantes", Namespace="http://schemas.datacontract.org/2004/07/TrabalhoWeb2.Models")]
    [System.SerializableAttribute()]
    public partial class Participantes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgendaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParticipantesIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgendaId {
            get {
                return this.AgendaIdField;
            }
            set {
                if ((this.AgendaIdField.Equals(value) != true)) {
                    this.AgendaIdField = value;
                    this.RaisePropertyChanged("AgendaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParticipantesID {
            get {
                return this.ParticipantesIDField;
            }
            set {
                if ((this.ParticipantesIDField.Equals(value) != true)) {
                    this.ParticipantesIDField = value;
                    this.RaisePropertyChanged("ParticipantesID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioID {
            get {
                return this.UsuarioIDField;
            }
            set {
                if ((this.UsuarioIDField.Equals(value) != true)) {
                    this.UsuarioIDField = value;
                    this.RaisePropertyChanged("UsuarioID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSAula.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/verificaLogin", ReplyAction="http://tempuri.org/IService1/verificaLoginResponse")]
        bool verificaLogin(string usuario, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/verificaLogin", ReplyAction="http://tempuri.org/IService1/verificaLoginResponse")]
        System.Threading.Tasks.Task<bool> verificaLoginAsync(string usuario, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/adicionaUsuario", ReplyAction="http://tempuri.org/IService1/adicionaUsuarioResponse")]
        bool adicionaUsuario(TrabalhoWeb2.WSAula.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/adicionaUsuario", ReplyAction="http://tempuri.org/IService1/adicionaUsuarioResponse")]
        System.Threading.Tasks.Task<bool> adicionaUsuarioAsync(TrabalhoWeb2.WSAula.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/adicionaAgenda", ReplyAction="http://tempuri.org/IService1/adicionaAgendaResponse")]
        bool adicionaAgenda(TrabalhoWeb2.WSAula.Agenda agenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/adicionaAgenda", ReplyAction="http://tempuri.org/IService1/adicionaAgendaResponse")]
        System.Threading.Tasks.Task<bool> adicionaAgendaAsync(TrabalhoWeb2.WSAula.Agenda agenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/adicionaParticipante", ReplyAction="http://tempuri.org/IService1/adicionaParticipanteResponse")]
        bool adicionaParticipante(TrabalhoWeb2.WSAula.Participantes participante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/adicionaParticipante", ReplyAction="http://tempuri.org/IService1/adicionaParticipanteResponse")]
        System.Threading.Tasks.Task<bool> adicionaParticipanteAsync(TrabalhoWeb2.WSAula.Participantes participante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/lstCompromissos", ReplyAction="http://tempuri.org/IService1/lstCompromissosResponse")]
        System.Collections.Generic.List<TrabalhoWeb2.WSAula.Agenda> lstCompromissos(int IdUsuario, int qtd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/lstCompromissos", ReplyAction="http://tempuri.org/IService1/lstCompromissosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TrabalhoWeb2.WSAula.Agenda>> lstCompromissosAsync(int IdUsuario, int qtd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/lstUsuario", ReplyAction="http://tempuri.org/IService1/lstUsuarioResponse")]
        System.Collections.Generic.List<TrabalhoWeb2.WSAula.Usuario> lstUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/lstUsuario", ReplyAction="http://tempuri.org/IService1/lstUsuarioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TrabalhoWeb2.WSAula.Usuario>> lstUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/lstParticipantesCompromisso", ReplyAction="http://tempuri.org/IService1/lstParticipantesCompromissoResponse")]
        System.Collections.Generic.List<TrabalhoWeb2.WSAula.Participantes> lstParticipantesCompromisso(int idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/lstParticipantesCompromisso", ReplyAction="http://tempuri.org/IService1/lstParticipantesCompromissoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TrabalhoWeb2.WSAula.Participantes>> lstParticipantesCompromissoAsync(int idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/lstUsuarioParticipantes", ReplyAction="http://tempuri.org/IService1/lstUsuarioParticipantesResponse")]
        System.Collections.Generic.List<TrabalhoWeb2.WSAula.Usuario> lstUsuarioParticipantes(System.Collections.Generic.List<TrabalhoWeb2.WSAula.Participantes> lstPart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/lstUsuarioParticipantes", ReplyAction="http://tempuri.org/IService1/lstUsuarioParticipantesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TrabalhoWeb2.WSAula.Usuario>> lstUsuarioParticipantesAsync(System.Collections.Generic.List<TrabalhoWeb2.WSAula.Participantes> lstPart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retornaCompromisso", ReplyAction="http://tempuri.org/IService1/retornaCompromissoResponse")]
        TrabalhoWeb2.WSAula.Agenda retornaCompromisso(int idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retornaCompromisso", ReplyAction="http://tempuri.org/IService1/retornaCompromissoResponse")]
        System.Threading.Tasks.Task<TrabalhoWeb2.WSAula.Agenda> retornaCompromissoAsync(int idAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retornaUsuarioPorID", ReplyAction="http://tempuri.org/IService1/retornaUsuarioPorIDResponse")]
        TrabalhoWeb2.WSAula.Usuario retornaUsuarioPorID(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retornaUsuarioPorID", ReplyAction="http://tempuri.org/IService1/retornaUsuarioPorIDResponse")]
        System.Threading.Tasks.Task<TrabalhoWeb2.WSAula.Usuario> retornaUsuarioPorIDAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retornaUsuarioPorLOGIN", ReplyAction="http://tempuri.org/IService1/retornaUsuarioPorLOGINResponse")]
        TrabalhoWeb2.WSAula.Usuario retornaUsuarioPorLOGIN(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retornaUsuarioPorLOGIN", ReplyAction="http://tempuri.org/IService1/retornaUsuarioPorLOGINResponse")]
        System.Threading.Tasks.Task<TrabalhoWeb2.WSAula.Usuario> retornaUsuarioPorLOGINAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/verificaParticipante", ReplyAction="http://tempuri.org/IService1/verificaParticipanteResponse")]
        bool verificaParticipante(int IdUsuario, int IdAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/verificaParticipante", ReplyAction="http://tempuri.org/IService1/verificaParticipanteResponse")]
        System.Threading.Tasks.Task<bool> verificaParticipanteAsync(int IdUsuario, int IdAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/excluirParticipantes", ReplyAction="http://tempuri.org/IService1/excluirParticipantesResponse")]
        bool excluirParticipantes(int IdUsuario, int IdAgenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/excluirParticipantes", ReplyAction="http://tempuri.org/IService1/excluirParticipantesResponse")]
        System.Threading.Tasks.Task<bool> excluirParticipantesAsync(int IdUsuario, int IdAgenda);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TrabalhoWeb2.WSAula.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TrabalhoWeb2.WSAula.IService1>, TrabalhoWeb2.WSAula.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool verificaLogin(string usuario, string senha) {
            return base.Channel.verificaLogin(usuario, senha);
        }
        
        public System.Threading.Tasks.Task<bool> verificaLoginAsync(string usuario, string senha) {
            return base.Channel.verificaLoginAsync(usuario, senha);
        }
        
        public bool adicionaUsuario(TrabalhoWeb2.WSAula.Usuario usuario) {
            return base.Channel.adicionaUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> adicionaUsuarioAsync(TrabalhoWeb2.WSAula.Usuario usuario) {
            return base.Channel.adicionaUsuarioAsync(usuario);
        }
        
        public bool adicionaAgenda(TrabalhoWeb2.WSAula.Agenda agenda) {
            return base.Channel.adicionaAgenda(agenda);
        }
        
        public System.Threading.Tasks.Task<bool> adicionaAgendaAsync(TrabalhoWeb2.WSAula.Agenda agenda) {
            return base.Channel.adicionaAgendaAsync(agenda);
        }
        
        public bool adicionaParticipante(TrabalhoWeb2.WSAula.Participantes participante) {
            return base.Channel.adicionaParticipante(participante);
        }
        
        public System.Threading.Tasks.Task<bool> adicionaParticipanteAsync(TrabalhoWeb2.WSAula.Participantes participante) {
            return base.Channel.adicionaParticipanteAsync(participante);
        }
        
        public System.Collections.Generic.List<TrabalhoWeb2.WSAula.Agenda> lstCompromissos(int IdUsuario, int qtd) {
            return base.Channel.lstCompromissos(IdUsuario, qtd);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TrabalhoWeb2.WSAula.Agenda>> lstCompromissosAsync(int IdUsuario, int qtd) {
            return base.Channel.lstCompromissosAsync(IdUsuario, qtd);
        }
        
        public System.Collections.Generic.List<TrabalhoWeb2.WSAula.Usuario> lstUsuario(int idUsuario) {
            return base.Channel.lstUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TrabalhoWeb2.WSAula.Usuario>> lstUsuarioAsync(int idUsuario) {
            return base.Channel.lstUsuarioAsync(idUsuario);
        }
        
        public System.Collections.Generic.List<TrabalhoWeb2.WSAula.Participantes> lstParticipantesCompromisso(int idAgenda) {
            return base.Channel.lstParticipantesCompromisso(idAgenda);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TrabalhoWeb2.WSAula.Participantes>> lstParticipantesCompromissoAsync(int idAgenda) {
            return base.Channel.lstParticipantesCompromissoAsync(idAgenda);
        }
        
        public System.Collections.Generic.List<TrabalhoWeb2.WSAula.Usuario> lstUsuarioParticipantes(System.Collections.Generic.List<TrabalhoWeb2.WSAula.Participantes> lstPart) {
            return base.Channel.lstUsuarioParticipantes(lstPart);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TrabalhoWeb2.WSAula.Usuario>> lstUsuarioParticipantesAsync(System.Collections.Generic.List<TrabalhoWeb2.WSAula.Participantes> lstPart) {
            return base.Channel.lstUsuarioParticipantesAsync(lstPart);
        }
        
        public TrabalhoWeb2.WSAula.Agenda retornaCompromisso(int idAgenda) {
            return base.Channel.retornaCompromisso(idAgenda);
        }
        
        public System.Threading.Tasks.Task<TrabalhoWeb2.WSAula.Agenda> retornaCompromissoAsync(int idAgenda) {
            return base.Channel.retornaCompromissoAsync(idAgenda);
        }
        
        public TrabalhoWeb2.WSAula.Usuario retornaUsuarioPorID(int idUsuario) {
            return base.Channel.retornaUsuarioPorID(idUsuario);
        }
        
        public System.Threading.Tasks.Task<TrabalhoWeb2.WSAula.Usuario> retornaUsuarioPorIDAsync(int idUsuario) {
            return base.Channel.retornaUsuarioPorIDAsync(idUsuario);
        }
        
        public TrabalhoWeb2.WSAula.Usuario retornaUsuarioPorLOGIN(string login) {
            return base.Channel.retornaUsuarioPorLOGIN(login);
        }
        
        public System.Threading.Tasks.Task<TrabalhoWeb2.WSAula.Usuario> retornaUsuarioPorLOGINAsync(string login) {
            return base.Channel.retornaUsuarioPorLOGINAsync(login);
        }
        
        public bool verificaParticipante(int IdUsuario, int IdAgenda) {
            return base.Channel.verificaParticipante(IdUsuario, IdAgenda);
        }
        
        public System.Threading.Tasks.Task<bool> verificaParticipanteAsync(int IdUsuario, int IdAgenda) {
            return base.Channel.verificaParticipanteAsync(IdUsuario, IdAgenda);
        }
        
        public bool excluirParticipantes(int IdUsuario, int IdAgenda) {
            return base.Channel.excluirParticipantes(IdUsuario, IdAgenda);
        }
        
        public System.Threading.Tasks.Task<bool> excluirParticipantesAsync(int IdUsuario, int IdAgenda) {
            return base.Channel.excluirParticipantesAsync(IdUsuario, IdAgenda);
        }
    }
}
